apiVersion: 1
datasources:
  - name: Postgres-HousePrices
    type: postgres
    access: proxy
    url: postgres:5432
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      database: airflow
      sslmode: disable
      postgresVersion: 1500
